const express = require('express');
const cors = require('cors');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const { execSync } = require('child_process');

const app = express();
const port = process.env.PORT || 3000;

// Enable CORS and JSON parsing
app.use(cors());
app.use(express.json());

// Serve static files from the current directory
app.use(express.static(__dirname));

// Redirect root to code.html
app.get('/', (req, res) => {
    res.redirect('/code.html');
});

// Ensure upload directory exists
const uploadDir = path.join(__dirname, 'images/uploads');
if (!fs.existsSync(uploadDir)) {
    fs.mkdirSync(uploadDir, { recursive: true });
}

// Configure multer for file uploads
const storage = multer.diskStorage({
    destination: function (req, file, cb) {
        cb(null, uploadDir);
    },
    filename: function (req, file, cb) {
        // Keep original extension, generate a safe temporary name
        const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1E9);
        cb(null, 'temp-' + uniqueSuffix + path.extname(file.originalname));
    }
});

const upload = multer({ storage: storage });

// API Endpoint to handle product upload
app.post('/api/upload', upload.single('productImage'), (req, res) => {
    try {
        if (!req.file) {
            return res.status(400).json({ success: false, message: 'No image provided' });
        }

        const category = req.body.category;
        const title = req.body.title; // Optional, currently generated by category

        if (!category) {
            fs.unlinkSync(req.file.path); // Cleanup
            return res.status(400).json({ success: false, message: 'Category is required' });
        }

        console.log(`Received upload for category: ${category}, File: ${req.file.filename}`);

        // Run the import_images.js script to process the uploaded file
        console.log('Running import_images.js...');
        execSync(`node scripts/import_images.js ${category}`, { stdio: 'inherit' });

        // Run the build_catalog.js script to update the HTML
        console.log('Running build_catalog.js...');
        execSync('node scripts/build_catalog.js', { stdio: 'inherit' });

        // Cleanup the uploads folder just in case (import_images.js might copy, not move)
        if (fs.existsSync(req.file.path)) {
            fs.unlinkSync(req.file.path);
        }

        res.json({ success: true, message: 'Product published successfully!' });
    } catch (error) {
        console.error('Upload Error:', error);
        res.status(500).json({ success: false, message: 'Internal server error during publish.' });
    }
});

// API Endpoint to list all catalog products
app.get('/api/products', (req, res) => {
    try {
        const productsDir = path.join(__dirname, 'images/catalog/products');
        if (!fs.existsSync(productsDir)) {
            return res.json({ success: true, products: [] });
        }
        
        const files = fs.readdirSync(productsDir);
        const products = files.map((file, index) => {
            const stats = fs.statSync(path.join(productsDir, file));
            const categoryMatch = file.match(/^([a-zA-Z]+)/);
            const category = categoryMatch ? categoryMatch[1].toLowerCase() : 'uncategorized';
            
            return {
                id: file, // Use filename as ID
                image: `images/catalog/products/${file}`,
                title: file,
                category: category,
                date: stats.mtime.toLocaleDateString('en-IN')
            };
        });

        // Sort by newest first
        products.sort((a, b) => fs.statSync(path.join(__dirname, b.image)).mtimeMs - fs.statSync(path.join(__dirname, a.image)).mtimeMs);
        
        res.json({ success: true, products });
    } catch (error) {
        console.error('List Products Error:', error);
        res.status(500).json({ success: false, message: 'Internal server error.' });
    }
});

// API Endpoint to delete a product
app.post('/api/delete', (req, res) => {
    try {
        const { filename } = req.body;
        if (!filename) {
            return res.status(400).json({ success: false, message: 'Filename is required' });
        }

        const filePath = path.join(__dirname, 'images/catalog/products', filename);
        
        // Prevent directory traversal attacks
        if (!filePath.startsWith(path.join(__dirname, 'images/catalog/products'))) {
             return res.status(403).json({ success: false, message: 'Forbidden' });
        }

        if (fs.existsSync(filePath)) {
            fs.unlinkSync(filePath);
            console.log(`Deleted file: ${filename}`);
            
            // Rebuild the catalog
            console.log('Running build_catalog.js after deletion...');
            execSync('node scripts/build_catalog.js', { stdio: 'inherit' });
            
            res.json({ success: true, message: 'Product deleted successfully' });
        } else {
            res.status(404).json({ success: false, message: 'File not found' });
        }
    } catch (error) {
        console.error('Delete Error:', error);
        res.status(500).json({ success: false, message: 'Internal server error during deletion.' });
    }
});

// Start the server
app.listen(port, () => {
    console.log(`=========================================`);
    console.log(`🚀 Shivshankar Curtain Mall Server Running`);
    console.log(`🌐 Visit: http://localhost:${port}/code.html`);
    console.log(`=========================================`);
});
